FROM arm64v8/ubuntu:xenial

ENV ARCH=aarch64 DIST=xenial

# inherited by build scripts
ARG VERBOSE=0

COPY ./install-deps-ubuntu.sh /
RUN bash -x /install-deps-ubuntu.sh

COPY ./install-cmake.sh /
RUN bash -x /install-cmake.sh
